# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: discovery.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='discovery.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0f\x64iscovery.proto\":\n\x0bRegisterReq\x12\x0c\n\x04role\x18\x01 \x01(\t\x12\x11\n\ttopiclist\x18\x02 \x01(\t\x12\n\n\x02id\x18\x03 \x01(\t\"\x1e\n\x0cRegisterResp\x12\x0e\n\x06result\x18\x01 \x01(\t\"\x0c\n\nIsReadyReq\"\x1c\n\x0bIsReadyResp\x12\r\n\x05reply\x18\x01 \x01(\x08\"(\n\x13LookupPubByTopicReq\x12\x11\n\ttopiclist\x18\x01 \x01(\t\"#\n\x14LookupPubByTopicResp\x12\x0b\n\x03ids\x18\x01 \x03(\t\"\xa4\x01\n\x0c\x44iscoveryReq\x12\x1b\n\x08msg_type\x18\x01 \x01(\x0e\x32\t.MsgTypes\x12$\n\x0cregister_req\x18\x02 \x01(\x0b\x32\x0c.RegisterReqH\x00\x12\x1f\n\x08is_ready\x18\x03 \x01(\x0b\x32\x0b.IsReadyReqH\x00\x12%\n\x05topic\x18\x04 \x01(\x0b\x32\x14.LookupPubByTopicReqH\x00\x42\t\n\x07\x43ontent\"\xa8\x01\n\rDiscoveryResp\x12\x1b\n\x08msg_type\x18\x01 \x01(\x0e\x32\t.MsgTypes\x12&\n\rregister_resp\x18\x02 \x01(\x0b\x32\r.RegisterRespH\x00\x12 \n\x08is_ready\x18\x03 \x01(\x0b\x32\x0c.IsReadyRespH\x00\x12%\n\x04resp\x18\x04 \x01(\x0b\x32\x15.LookupPubByTopicRespH\x00\x42\t\n\x07\x43ontent*`\n\x08MsgTypes\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0c\n\x08REGISTER\x10\x01\x12\x0b\n\x07ISREADY\x10\x02\x12\x17\n\x13LOOKUP_PUB_BY_TOPIC\x10\x03\x12\x13\n\x0fLOOKUP_ALL_PUBS\x10\x04\x62\x06proto3')
)

_MSGTYPES = _descriptor.EnumDescriptor(
  name='MsgTypes',
  full_name='MsgTypes',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='REGISTER', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ISREADY', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LOOKUP_PUB_BY_TOPIC', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LOOKUP_ALL_PUBS', index=4, number=4,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=572,
  serialized_end=668,
)
_sym_db.RegisterEnumDescriptor(_MSGTYPES)

MsgTypes = enum_type_wrapper.EnumTypeWrapper(_MSGTYPES)
UNKNOWN = 0
REGISTER = 1
ISREADY = 2
LOOKUP_PUB_BY_TOPIC = 3
LOOKUP_ALL_PUBS = 4



_REGISTERREQ = _descriptor.Descriptor(
  name='RegisterReq',
  full_name='RegisterReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='role', full_name='RegisterReq.role', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='topiclist', full_name='RegisterReq.topiclist', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='id', full_name='RegisterReq.id', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=77,
)


_REGISTERRESP = _descriptor.Descriptor(
  name='RegisterResp',
  full_name='RegisterResp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='RegisterResp.result', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=79,
  serialized_end=109,
)


_ISREADYREQ = _descriptor.Descriptor(
  name='IsReadyReq',
  full_name='IsReadyReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=111,
  serialized_end=123,
)


_ISREADYRESP = _descriptor.Descriptor(
  name='IsReadyResp',
  full_name='IsReadyResp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='reply', full_name='IsReadyResp.reply', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=125,
  serialized_end=153,
)


_LOOKUPPUBBYTOPICREQ = _descriptor.Descriptor(
  name='LookupPubByTopicReq',
  full_name='LookupPubByTopicReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='topiclist', full_name='LookupPubByTopicReq.topiclist', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=155,
  serialized_end=195,
)


_LOOKUPPUBBYTOPICRESP = _descriptor.Descriptor(
  name='LookupPubByTopicResp',
  full_name='LookupPubByTopicResp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ids', full_name='LookupPubByTopicResp.ids', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=197,
  serialized_end=232,
)


_DISCOVERYREQ = _descriptor.Descriptor(
  name='DiscoveryReq',
  full_name='DiscoveryReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='msg_type', full_name='DiscoveryReq.msg_type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='register_req', full_name='DiscoveryReq.register_req', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='is_ready', full_name='DiscoveryReq.is_ready', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='topic', full_name='DiscoveryReq.topic', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='Content', full_name='DiscoveryReq.Content',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=235,
  serialized_end=399,
)


_DISCOVERYRESP = _descriptor.Descriptor(
  name='DiscoveryResp',
  full_name='DiscoveryResp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='msg_type', full_name='DiscoveryResp.msg_type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='register_resp', full_name='DiscoveryResp.register_resp', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='is_ready', full_name='DiscoveryResp.is_ready', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='resp', full_name='DiscoveryResp.resp', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='Content', full_name='DiscoveryResp.Content',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=402,
  serialized_end=570,
)

_DISCOVERYREQ.fields_by_name['msg_type'].enum_type = _MSGTYPES
_DISCOVERYREQ.fields_by_name['register_req'].message_type = _REGISTERREQ
_DISCOVERYREQ.fields_by_name['is_ready'].message_type = _ISREADYREQ
_DISCOVERYREQ.fields_by_name['topic'].message_type = _LOOKUPPUBBYTOPICREQ
_DISCOVERYREQ.oneofs_by_name['Content'].fields.append(
  _DISCOVERYREQ.fields_by_name['register_req'])
_DISCOVERYREQ.fields_by_name['register_req'].containing_oneof = _DISCOVERYREQ.oneofs_by_name['Content']
_DISCOVERYREQ.oneofs_by_name['Content'].fields.append(
  _DISCOVERYREQ.fields_by_name['is_ready'])
_DISCOVERYREQ.fields_by_name['is_ready'].containing_oneof = _DISCOVERYREQ.oneofs_by_name['Content']
_DISCOVERYREQ.oneofs_by_name['Content'].fields.append(
  _DISCOVERYREQ.fields_by_name['topic'])
_DISCOVERYREQ.fields_by_name['topic'].containing_oneof = _DISCOVERYREQ.oneofs_by_name['Content']
_DISCOVERYRESP.fields_by_name['msg_type'].enum_type = _MSGTYPES
_DISCOVERYRESP.fields_by_name['register_resp'].message_type = _REGISTERRESP
_DISCOVERYRESP.fields_by_name['is_ready'].message_type = _ISREADYRESP
_DISCOVERYRESP.fields_by_name['resp'].message_type = _LOOKUPPUBBYTOPICRESP
_DISCOVERYRESP.oneofs_by_name['Content'].fields.append(
  _DISCOVERYRESP.fields_by_name['register_resp'])
_DISCOVERYRESP.fields_by_name['register_resp'].containing_oneof = _DISCOVERYRESP.oneofs_by_name['Content']
_DISCOVERYRESP.oneofs_by_name['Content'].fields.append(
  _DISCOVERYRESP.fields_by_name['is_ready'])
_DISCOVERYRESP.fields_by_name['is_ready'].containing_oneof = _DISCOVERYRESP.oneofs_by_name['Content']
_DISCOVERYRESP.oneofs_by_name['Content'].fields.append(
  _DISCOVERYRESP.fields_by_name['resp'])
_DISCOVERYRESP.fields_by_name['resp'].containing_oneof = _DISCOVERYRESP.oneofs_by_name['Content']
DESCRIPTOR.message_types_by_name['RegisterReq'] = _REGISTERREQ
DESCRIPTOR.message_types_by_name['RegisterResp'] = _REGISTERRESP
DESCRIPTOR.message_types_by_name['IsReadyReq'] = _ISREADYREQ
DESCRIPTOR.message_types_by_name['IsReadyResp'] = _ISREADYRESP
DESCRIPTOR.message_types_by_name['LookupPubByTopicReq'] = _LOOKUPPUBBYTOPICREQ
DESCRIPTOR.message_types_by_name['LookupPubByTopicResp'] = _LOOKUPPUBBYTOPICRESP
DESCRIPTOR.message_types_by_name['DiscoveryReq'] = _DISCOVERYREQ
DESCRIPTOR.message_types_by_name['DiscoveryResp'] = _DISCOVERYRESP
DESCRIPTOR.enum_types_by_name['MsgTypes'] = _MSGTYPES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RegisterReq = _reflection.GeneratedProtocolMessageType('RegisterReq', (_message.Message,), dict(
  DESCRIPTOR = _REGISTERREQ,
  __module__ = 'discovery_pb2'
  # @@protoc_insertion_point(class_scope:RegisterReq)
  ))
_sym_db.RegisterMessage(RegisterReq)

RegisterResp = _reflection.GeneratedProtocolMessageType('RegisterResp', (_message.Message,), dict(
  DESCRIPTOR = _REGISTERRESP,
  __module__ = 'discovery_pb2'
  # @@protoc_insertion_point(class_scope:RegisterResp)
  ))
_sym_db.RegisterMessage(RegisterResp)

IsReadyReq = _reflection.GeneratedProtocolMessageType('IsReadyReq', (_message.Message,), dict(
  DESCRIPTOR = _ISREADYREQ,
  __module__ = 'discovery_pb2'
  # @@protoc_insertion_point(class_scope:IsReadyReq)
  ))
_sym_db.RegisterMessage(IsReadyReq)

IsReadyResp = _reflection.GeneratedProtocolMessageType('IsReadyResp', (_message.Message,), dict(
  DESCRIPTOR = _ISREADYRESP,
  __module__ = 'discovery_pb2'
  # @@protoc_insertion_point(class_scope:IsReadyResp)
  ))
_sym_db.RegisterMessage(IsReadyResp)

LookupPubByTopicReq = _reflection.GeneratedProtocolMessageType('LookupPubByTopicReq', (_message.Message,), dict(
  DESCRIPTOR = _LOOKUPPUBBYTOPICREQ,
  __module__ = 'discovery_pb2'
  # @@protoc_insertion_point(class_scope:LookupPubByTopicReq)
  ))
_sym_db.RegisterMessage(LookupPubByTopicReq)

LookupPubByTopicResp = _reflection.GeneratedProtocolMessageType('LookupPubByTopicResp', (_message.Message,), dict(
  DESCRIPTOR = _LOOKUPPUBBYTOPICRESP,
  __module__ = 'discovery_pb2'
  # @@protoc_insertion_point(class_scope:LookupPubByTopicResp)
  ))
_sym_db.RegisterMessage(LookupPubByTopicResp)

DiscoveryReq = _reflection.GeneratedProtocolMessageType('DiscoveryReq', (_message.Message,), dict(
  DESCRIPTOR = _DISCOVERYREQ,
  __module__ = 'discovery_pb2'
  # @@protoc_insertion_point(class_scope:DiscoveryReq)
  ))
_sym_db.RegisterMessage(DiscoveryReq)

DiscoveryResp = _reflection.GeneratedProtocolMessageType('DiscoveryResp', (_message.Message,), dict(
  DESCRIPTOR = _DISCOVERYRESP,
  __module__ = 'discovery_pb2'
  # @@protoc_insertion_point(class_scope:DiscoveryResp)
  ))
_sym_db.RegisterMessage(DiscoveryResp)


# @@protoc_insertion_point(module_scope)
